printf ("	<div class=\"container\">");
printf ("		<div class=\"card card-container\">");
printf ("			<img id=\"profile-img\" class=\"profile-img-card\" src=\"http://ssl.gstatic.com/accounts/ui/avatar_2x.png\" />");
printf ("	        <p id=\"profile-name\" class=\"profile-name-card\"></p>");
printf ("			<form class=\"form-signin\" method=\"POST\" action=\"gmtUmlRequestRegistration.cgi\">");
printf ("				<h2 class=\"form-signin-heading\">%s</h2>", GmtUmlGetWebUserInterface (gmtUmlForgotPassword, gmtUmlLanguage));
printf ("				<label for=\"inputName\" class=\"sr-only\">%s</label>", GmtUmlGetWebUserInterface (gmtUmlUsername, gmtUmlLanguage));
printf ("				<input type=\"text\" name=\"nickname\" id=\"inputNickname\" class=\"form-control\" placeholder=\"%s\" required autofocus>", GmtUmlGetWebUserInterface (gmtUmlUsername, gmtUmlLanguage));
printf ("				<label for=\"inputEmail\" class=\"sr-only\">%s</label>", GmtUmlGetWebUserInterface (gmtUmlEmail, gmtUmlLanguage));
printf ("				<input type=\"email\" name=\"nickname\" id=\"inputNickname\" class=\"form-control\" placeholder=\"%s\" required autofocus>", GmtUmlGetWebUserInterface (gmtUmlEmail, gmtUmlLanguage));
printf ("				<input type=\"hidden\" name=\"gmtUmlConfigurationFileName\" value=\"%s\">", gmtUmlConfigurationFileName);
printf ("				<input type=\"hidden\" name=\"gmtUmlLanguage\" value=\"%s\">", gmtUmlLanguage);
printf ("				<button class=\"btn btn-lg btn-primary btn-block btn-signin\" type=\"submit\">%s</button>", GmtUmlGetWebUserInterface (gmtUmlResetPassword, gmtUmlLanguage));
printf ("			</form>");
printf ("			<a href=\"javascript:history.back()\" class=\"forgot-password\">%s</a>", GmtUmlGetWebUserInterface (gmtUmlBack, gmtUmlLanguage));
printf ("		</div>");
printf ("	</div>");
printf ("	<div class=\"footer\">");
printf ("		<a href=\"mailto:gabriel.tavora@poli.ufrj.br\">© 2017 Gabriel Montenegro Tavora.</a>");
printf ("	</div>");
printf ("	<script src=\"jquery-3.2.1.js\"></script>");
printf ("	<script src=\"bootstrap/js/bootstrap.bundle.min.js\"></script>");
printf ("</body>");